services:
  - type: web
    name: drive-download-tool
    env: node
    buildCommand: npm install --ignore-scripts
    startCommand: node server.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer